export const startData = {
  companyName: '',
  incorporation: '',
  rcNumber: '',
  industry: '',
  description: '',
  fundingInterest: '',
  companyEmail: '',
  companyWebsite: '',
  companyAddress: '',
  companyPhone: '',
  founderName: '',
  founderEmail: '',
  founderAddress: '',
  founderMobile: '',
  founderNo: '',
  certificate: new FormData(),
  logo: new File([''], 'logo.png', { type: 'image/png' }),
};
