#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export PATH="/opt/homebrew/bin:$PATH"

spinner() {
  local pid=$!
  local delay=0.1
  local spinstr='|/-\'
  while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
    local temp=${spinstr#?}
    printf " [%c]  " "$spinstr"
    local spinstr=$temp${spinstr%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done
  printf "    \b\b\b\b"
}

# Run pnpm format with a spinner
(pnpm format) & spinner
echo "Formatting completed!"

# Run pnpm lint with a spinner
(pnpm lint) & spinner
echo "Linting completed!"